"""Auto-generate skills/README.md + docs/README.md từ list files."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def extract_title(md_file: Path) -> str:
    """Lấy heading H1. Fallback: filename stem."""
    for line in md_file.read_text().splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return md_file.stem


def build_index(dir_path: Path, title: str) -> str:
    """Build markdown index of all *.md files in dir (sorted, skip README.md)."""
    files = sorted(p for p in dir_path.glob("*.md") if p.name != "README.md")
    lines = [
        f"# {title}",
        "",
        "Auto-generated by `scripts/generate_index.py` — không sửa tay.",
        "",
    ]
    for f in files:
        title_text = extract_title(f)
        lines.append(f"- [{title_text}]({f.name})")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repo root (default cwd)")
    parser.add_argument("--check", action="store_true", help="Fail if changes needed")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    targets = [
        (root / "skills", "Skills — Quy tắc viết Wiki"),
        (root / "docs", "Docs — Tham chiếu công ty"),
    ]
    changed = []
    for d, title in targets:
        if not d.exists():
            continue
        new_content = build_index(d, title)
        readme = d / "README.md"
        old_content = readme.read_text() if readme.exists() else ""
        if new_content != old_content:
            if args.check:
                changed.append(str(readme))
            else:
                readme.write_text(new_content)
                print(f"✓ Updated {readme}")

    if args.check and changed:
        print(f"❌ Cần regenerate: {changed}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
